FROM node:12.22.9-alpine
#Crear directorio para la aplicacion 
WORKDIR /app
# Importar el archivo json del proyecto
# COPY package*.json ./
# #Instalar complementos del archivo

# RUN npm install


#Copiar todos los archivos del proyecto
COPY . .


#Publicar  puerto

#EXPOSE 5000 
CMD ["node","servidor.js"]